# Generated by Django 5.0.4 on 2024-04-11 22:31

from django.db import migrations  # type: ignore # noqa: F401


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="new_content_is_html",
            new_name="news_content_is_html",
        ),
    ]
