# Generated by Django 5.0.4 on 2024-04-16 20:41

import django.db.models.deletion  # type: ignore # noqa: F401
from django.conf import settings  # type: ignore # noqa: F401
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_rename_new_content_is_html_news_news_content_is_html"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.category",
            ),
        ),
    ]
