# Generated by Django 5.0.4 on 2024-04-16 20:41

from django.db import migrations, models  # type: ignore # noqa: F401


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_author_alter_news_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
