# Generated by Django 5.0.4 on 2024-05-31 18:33

from django.db import migrations, models  # type: ignore # noqa: F401


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="cover",
            field=models.ImageField(
                blank=True, upload_to="news/covers/%Y/%m/%d/"),
        ),
    ]
